
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Fans_Wechat
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public string openid { get; set; }

    public string nickname { get; set; }

    public string language { get; set; }

    public int sex { get; set; }

    public string province { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public string headimgurl { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public string Precision { get; set; }

    public string remark { get; set; }

    public string unionid { get; set; }

    public System.DateTime LOCATIONUpdateTime { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
