
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Keywords
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public int ApplyType { get; set; }

    public string TypeIDs { get; set; }

    public string Title { get; set; }

    public string ReplaceContent { get; set; }

    public int ReplaceCount { get; set; }

    public int IsShow { get; set; }

    public long ShowIndex { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
