
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Permission
{

    public long ID { get; set; }

    public int TypeID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string MenuName { get; set; }

    public string MenuLink { get; set; }

    public string PageName { get; set; }

    public string ShowIndex { get; set; }

    public string Icon { get; set; }

    public int IsShow { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
