
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Page
{

    public long ID { get; set; }

    public string PageName { get; set; }

    public int BuildType { get; set; }

    public long TypeID { get; set; }

    public int PageKind { get; set; }

    public string SavePath { get; set; }

    public string ExtensionName { get; set; }

    public string Summary { get; set; }

    public string PageCode { get; set; }

    public int CanBuild { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastUpdateTime { get; set; }

}

}
