
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_RedPack_Order
{

    public long ID { get; set; }

    public long red_packID { get; set; }

    public long UserID { get; set; }

    public long MechantID { get; set; }

    public long AgencyID { get; set; }

    public string re_openid { get; set; }

    public string mch_billno { get; set; }

    public string detail_id { get; set; }

    public long red_money { get; set; }

    public string status { get; set; }

    public System.DateTime CreateTime { get; set; }

}

}
