
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_SiteSetting
{

    public int ID { get; set; }

    public string SiteAddress { get; set; }

    public string Email { get; set; }

    public string Watermark { get; set; }

    public int EnabelWatermark { get; set; }

    public string MailServer { get; set; }

    public int MailPort { get; set; }

    public string MailAccount { get; set; }

    public string MailPassword { get; set; }

    public string SystemTopBar { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
