
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Statistics
{

    public long ID { get; set; }

    public long PID { get; set; }

    public int Type { get; set; }

    public System.DateTime CreateTime { get; set; }

}

}
