
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Spider_Log
{

    public long ID { get; set; }

    public long SpiderID { get; set; }

    public long TotalUrl { get; set; }

    public long SuccessUrl { get; set; }

}

}
