
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_User
{

    public long ID { get; set; }

    public string HeadImgUrl { get; set; }

    public string Mobile { get; set; }

    public string Mail { get; set; }

    public string UserName { get; set; }

    public string UserPwd { get; set; }

    public int Gender { get; set; }

    public int Role { get; set; }

    public string Permission { get; set; }

    public int CountryID { get; set; }

    public int ProvinceID { get; set; }

    public int DistrictID { get; set; }

    public int CityID { get; set; }

    public string Address { get; set; }

    public int LockFlag { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
