
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Video_Type
{

    public long ID { get; set; }

    public string Name { get; set; }

    public string Summary { get; set; }

    public string Image { get; set; }

    public long PID { get; set; }

    public int IsShow { get; set; }

    public long ShowIndex { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
