
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_FriendLink
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public string Title { get; set; }

    public string KeyWords { get; set; }

    public string Summary { get; set; }

    public string Info { get; set; }

    public int Recommend { get; set; }

    public string SiteUrl { get; set; }

    public string DefaultImg { get; set; }

    public decimal Score { get; set; }

    public int IsShow { get; set; }

    public long LookCount { get; set; }

    public long ShowIndex { get; set; }

    public int CanReply { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
