
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Message
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public int Platform { get; set; }

    public int Status { get; set; }

    public string Title { get; set; }

    public string Mail { get; set; }

    public string Mobile { get; set; }

    public string Message { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
