
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Page_Build_Config
{

    public long ID { get; set; }

    public long PageTypeID { get; set; }

    public long PageID { get; set; }

    public System.DateTime StartTime { get; set; }

    public System.DateTime EndTime { get; set; }

    public int BuildType { get; set; }

    public string DataTypeIDs { get; set; }

    public System.DateTime CreateTime { get; set; }

}

}
