
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Permission_Type
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string Icon { get; set; }

    public int ShowIndex { get; set; }

    public int IsShow { get; set; }

}

}
