
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Page_Type
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public int IsMaster { get; set; }

    public long SupportPlatform { get; set; }

    public string Author { get; set; }

    public string Website { get; set; }

    public string QQ { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Summary { get; set; }

    public string Name { get; set; }

    public string Name_En { get; set; }

    public string Images { get; set; }

    public int Version { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
