
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Photo_Item
{

    public long ID { get; set; }

    public long PhotoID { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string ImgUrl { get; set; }

    public long ShowIndex { get; set; }

}

}
