
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Platforms
{

    public int ID { get; set; }

    public long UserID { get; set; }

    public string Name { get; set; }

    public string Link { get; set; }

    public string Image { get; set; }

    public int Code { get; set; }

    public string APPKey { get; set; }

    public string APPSecret { get; set; }

    public string APPAdminID { get; set; }

    public string Access_token { get; set; }

    public System.DateTime Access_token_Expires_in { get; set; }

    public string Refresh_token { get; set; }

    public string APPPayID { get; set; }

    public string APPPayKey { get; set; }

    public string APPPayCert { get; set; }

    public string APPID { get; set; }

    public string APPName { get; set; }

    public string APPNumber { get; set; }

    public string jsapi_ticket { get; set; }

    public System.DateTime jsapi_ticket_Expires_in { get; set; }

    public string api_ticket { get; set; }

    public System.DateTime api_ticket_Expires_in { get; set; }

    public string PlatformConfig { get; set; }

    public string RecallUrl { get; set; }

    public string Remark { get; set; }

    public string JSSDK { get; set; }

    public string QRCode { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
