
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Page_Build_Task
{

    public long ID { get; set; }

    public string FullName { get; set; }

    public long TypeID { get; set; }

    public long PageID { get; set; }

    public string BuildEntity { get; set; }

    public long TotalCount { get; set; }

    public long BuildCount { get; set; }

    public int Status { get; set; }

    public string BuildHistory { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastUpdateTime { get; set; }

}

}
