
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_RedPack
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public long MerchantID { get; set; }

    public long AgencyID { get; set; }

    public string hb_type { get; set; }

    public string nick_name { get; set; }

    public string send_name { get; set; }

    public long current_amount { get; set; }

    public long total_amount { get; set; }

    public long min_value { get; set; }

    public long max_value { get; set; }

    public long Quantity { get; set; }

    public int total_num { get; set; }

    public string wishing { get; set; }

    public string act_name { get; set; }

    public string remark { get; set; }

    public string logo_imgurl { get; set; }

    public string share_content { get; set; }

    public string share_url { get; set; }

    public string share_imgurl { get; set; }

    public long GetLimit { get; set; }

    public long GetEmptyLimit { get; set; }

    public int IsShow { get; set; }

    public System.DateTime CreateTime { get; set; }

}

}
