
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Spider
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public string Title { get; set; }

    public string KeyWords { get; set; }

    public string TypeIDs { get; set; }

    public string Code { get; set; }

    public int Status { get; set; }

    public decimal Quality { get; set; }

    public string SourceUrls { get; set; }

    public string RuleConfig { get; set; }

    public int IsShow { get; set; }

    public long LookCount { get; set; }

    public int SpiderMode { get; set; }

    public string TargetPlatforms { get; set; }

    public long ExecutionInterval { get; set; }

    public System.DateTime LastStartTime { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
