
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_SynchronousTask
{

    public long ID { get; set; }

    public int Platform { get; set; }

    public int BusinessType { get; set; }

    public long RelationID { get; set; }

    public int OperationType { get; set; }

    public int Status { get; set; }

    public int MaxTry { get; set; }

    public int TriedCount { get; set; }

    public string Data { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastUpdateTime { get; set; }

}

}
