
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_Spider_News
{

    public long ID { get; set; }

    public long UserID { get; set; }

    public long Identifer { get; set; }

    public long SpiderID { get; set; }

    public string Title { get; set; }

    public string SourceUrl { get; set; }

    public string DefaultImage { get; set; }

    public string KeyWords { get; set; }

    public string Summary { get; set; }

    public string Info { get; set; }

    public int IsSync { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
