
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yycms.entity
{

using System;
    using System.Collections.Generic;
    
public partial class yy_SysError
{

    public long ID { get; set; }

    public string LogKey { get; set; }

    public string Message { get; set; }

    public string Source { get; set; }

    public string StackTrace { get; set; }

    public string HelpLink { get; set; }

    public string TargetSite { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
